---
title: "Titre"
author: "Degives Nicolas"
date: "Date"
output:
  html_document:
    code_folding: show
    collapsed: yes
    fig_caption: yes
    fig_height: 5
    fig_width: 6
    highlight: tango
    number_sections: yes
    smart: no
    theme: united
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '2'
    number_sections: yes
editor_options:
  chunk_output_type: console
---
  
```{r setup, include=FALSE}
rm(list=ls()) # Clean the workspace
library(pander)
library(readxl)
library(tidyverse)
library(knitr)
library(htmltools)

```

# Load and prepare the Data

## Import 

```{r, echo=TRUE}
data<- read_excel("Sorgho20_21_22_CIPF.xlsx")
head(data)
```

## Sort the columns

```{r, echo=TRUE}
cols_to_remove <- c('date_semis','date_recolte','lieu','precedent','traitement_semences','densite_semis')
data <- data[, ! names(data) %in% cols_to_remove, drop = F]
data$variete <- as.factor(data$variete)
pander(summary(data))
```

# Condition météo

```{r, echo=TRUE}
meteo <- read_excel("Sorgho20_21_22_CIPF.xlsx",sheet = "pluvio_temp")

mean_culture_rain <- c(
  mean((subset(meteo,annee==2020)$mean_rain)),
  mean((subset(meteo,annee==2021)$mean_rain)),
  mean((subset(meteo,annee==2022)$mean_rain))
)
mean_culture_rain <- data.frame(c(2020,2021,2022),mean_culture_rain)

#Plot precipitation
ggplot(data=meteo,aes(x=Mois))+
  facet_wrap(~annee)+
  geom_col(aes(y=mean_rain),width=0.5,fill='blue')+
  labs(title = "Pluviometrie")

#Plot temperature
ggplot(data = meteo, aes(x=Mois))+
  facet_wrap(~annee)+
  geom_col(aes(y=mean_temp,width=0.5),fill='red')+
  labs(title='Temperature')

#Diagramme ombrothermique
Mois = c('06/20','07/20','08/20','09/20','10/20',
         '06/21','07/21','08/21','09/21','10/21',
         '06/22','07/22','08/22','09/22','10/22')
plot.new()
par(mar=c(4,4,3,4))
position=barplot(meteo$mean_rain,col='cyan',names.arg = Mois,axes=F,ylab="",xlab="",main="Precipitation et température",ylim=c(0,200))
axis(2,col="black",at=seq(0, 200, by=25))
par(new=TRUE,mar=c(4,4,3,4))
maximal = max(position)+(position[2]-position[1])
plot(position,meteo$mean_temp,col="red",type="o",lwd=2,pch=16,axes=F,ylab="",xlab="",ylim=c(0,25), xlim=c(0,length(meteo$mean_temp)),yaxs ="i")
axis(4,col.axis='red',col='red')
box();grid()

```

# Inference sur les varietes

```{r, echo=TRUE}
ggplot(data=data,aes(x=variete,y=rendement_MS))+
  geom_bar(stat = 'identity')+ facet_wrap(~annee)+
  labs(x='Variété',
       y='rendement [T/ha]')
```

# Rendement des genotype par annee

```{r, echo=TRUE}
ggplot(data=data,aes(x=as.factor(annee),y=rendement_MS))+
  geom_bar(stat='identity')+
  facet_wrap(~variete)+
  labs(x='annee',
       y='rendement')
```