---
title: "Titre"
author: "Degives Nicolas"
date: "Date"
output:
  html_document:
    code_folding: show
    collapsed: yes
    fig_caption: yes
    fig_height: 5
    fig_width: 6
    highlight: tango
    number_sections: yes
    smart: no
    theme: united
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '2'
    number_sections: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
rm(list=ls()) # Clean the workspace
library(pander)
library(readxl)
library(tidyverse)
library(knitr)
library(htmltools)
library(lme4)
library(lmerTest)
```

# Load and prepare the Data

## Import 

```{r, echo=TRUE}
Amiggo <- read.csv("C:/Nico/Github/Memoire/End_growth_root_data/Amiggo.csv")
Biggben <- read.csv("C:/Nico/Github/Memoire/End_growth_root_data/Biggben.csv")
Hyperion <- read.csv("C:/Nico/Github/Memoire/End_growth_root_data/Hyperion.csv")
head(data)
```

## Mean dataset

**Network projected surface [cm3]**  
**Length [cm]**  
**Projected Surface [cm2]**  
**Surface [cm2]**  
**Volume [cm3]**  
**Mean diameter [cm]**  
**Insertion angle [degree]**  
**Insertion position [cm]**  
**N. of laterals**  
**Lateral density [root/cm]**  
**Mean interbranch distance [cm]**  


```{r, echo=TRUE}
global_data <- function(data){
  df_global <- data.frame()
  for (i in unique(data$image)) {
    df_global
  }
  return(df_global)
}

```

# 1

```{r, echo=TRUE}

```

# 1

```{r, echo=TRUE}

```

# 1

```{r, echo=TRUE}

```

# 1

```{r, echo=TRUE}

```

# 1

```{r, echo=TRUE}

```
